local Constants = {
	PLAYER_ATTRIBUTE = "SpinWheel",
    DATA_STORE_NAME = "SpinWheel_0",
    STATES = {
        CAN_CLAIM = "canClaim",
        CLAIMED = "claimed",
        TIMER = "timer",
    },
    REMOTE_EVENTS = {
        TIME_PASSED = "timePassed",
        CLAIM_REWARD = "claimReward",
    },
    REWARDS = {
        upgrade = {
            image = "",
            desc = "",
            name = "",
            displayName = "",
        },
        robux = {
            image = "",
            desc = "",
            name = "",
            displayName = "",
        },
        coins = {
            image = "",
            desc = "",
            name = "",
            displayName = "",
        }
    }
}

return Constants